theme: jekyll-theme-cayman

gem "github-pages", group: :jekyll_plugins

title: "Pandam"
description: "Canal de distribución para Pandam - Solu Inversiones S&M"
show_downloads: "true"

github:
  win32_url: https://github.com/liederivative/pandam-sym/build/win32/latest
  win64_url: https://github.com/liederivative/pandam-sym/build/win64/latest
  
